frontend/models/Post.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Post extends ActiveRecord
{
    public static function tableName()
    {
        return 'post';
    }
}

frontend/models/PostForm.php
<?php

namespace frontend\models;

use app\models\Post;
use yii\base\Model;
use yii\web\UploadedFile;

class PostForm extends Model
{
    public $id;
    public $title;
    public $content;
    public $image;
    public $owner_id;
    public $privacy_id;
    public $tags;
    public $time_id;
    public $comment;
    public $created_at;
    public $updated_at;

    public $year;
    public $month;
    public $day;

    public $imageFile;
    public $selected_tags;

    public function rules()
    {
        return [
            [['title', 'content', 'image', 'tags', 'year', 'month', 'day', 'privacy_id'], 'required'],
            ['title', 'string', 'min' => 3, 'max' => 100],
            ['year', 'integer', 'min' => 1000, 'max' => 2015],
            ['month', 'integer', 'min' => 1, 'max' => 12],
            ['day', 'integer', 'min' => 1, 'max' => 31],
            ['comment', 'boolean'],
            ['content', 'string'],
            ['imageFile', 'file', 'skipOnEmpty' => true, 'extensions' => 'png,jpg', 'checkExtensionByMimeType' => false],
        ];
    }

    public function attributeLabels()
    {
        return [
            'title' => 'Tiêu đề bài viết',
            'content' => 'Nội dung bài viết',
            'imageFile' => 'Hình ảnh minh họa',
            'tags' => 'Chủ đề',
            'year' => 'Năm',
            'month' => 'Tháng',
            'day' => 'Ngày',
        ];
    }

    public function create()
    {
        if ($this->upload()) {
            if (!$this->hasErrors()) {
                $model = new Post();
                $model->title = $this->title;
                $model->content = $this->content;
                $model->owner_id = $this->owner_id;
                $model->privacy_id = $this->privacy_id;
                $model->time_id = $this->time_id;
                $model->image = $this->image;
                $model->commentable = $this->comment;
                $model->created_at = $this->created_at;
                if ($model->save()) {
                    $this->id = $model->primaryKey;
                    return true;
                } else {
                    return false;
                }
            } else {
                return false;
            }
        } else {
            throw new \ErrorException("Can't upload the image !");
        }
    }

    public function update($id)
    {
        $model = Post::findOne(['id' => $id]);

        if ($this->upload()) {
            $model->image = $this->image;
        }
        if (!$this->hasErrors()) {
            $model->title = $this->title;
            $model->content = $this->content;
            $model->privacy_id = $this->privacy_id;
            $model->time_id = $this->time_id;
            $model->commentable = $this->comment;
            $model->updated_at = $this->updated_at;

            return $model->save();
        } else {
            return false;
        }
    }

    public function upload()
    {
        if (!$this->hasErrors()) {
            $this->imageFile = UploadedFile::getInstance($this, 'imageFile');
            if ($this->imageFile == null) {
                return false;
            }
            $this->imageFile->saveAs('images/' . $this->imageFile->baseName . '.' . $this->imageFile->extension);
            $this->image = $this->imageFile->baseName . '.' . $this->imageFile->extension;
            return true;
        } else {
            return false;
        }
    }


}

frontend/controllers/PostController.php
<?php

namespace frontend\controllers;

use app\models\Post;
use app\models\PostTag;
use app\models\Tag;
use app\models\Time;
use frontend\models\PostForm;
use frontend\models\PostQuery;
use frontend\models\TagQuery;
use frontend\models\TimeQuery;
use frontend\utils\Helper;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

class PostController extends Controller
{
    public function actionCreate()
    {
        if (!Helper::permission_request())
            throw new BadRequestHttpException();
        $model = new PostForm();
        $tag_query = TagQuery::getInstance();
        $tags = Tag::toMapString($tag_query->getAll());
        $model->owner_id = Yii::$app->user->getId();
        $model->created_at = Yii::$app->formatter->asDatetime(date('Y-d-m h:i:s'));
        if ($model->load(Yii::$app->request->post())) {
            $time_query = TimeQuery::getInstance();
            $model->time_id = $time_query->insert($model->day, $model->month, $model->year);
            if ($model->create()) {
                $tag_query->manage_tags($model->id, $model->tags);
                if ($model->privacy_id == 2) {
                    //TODO select friend
                    return $this->runAction('post/select-friend', ['post_id' => $model->id]);
                } else {
                    return $this->runAction('post/index');
                }
            } else {
                return $this->render('create', ['model' => $model, 'tags' => $tags, 'is_created' => false]);
            }
        }
        return $this->render('create', ['model' => $model, 'tags' => $tags]);
    }

    public function actionView($id)
    {
        $post_query = PostQuery::getInstance();
        $user_id = Yii::$app->user->getId();
        $post = $post_query->getPostById($id);
        if (!$post_query->readable($user_id, $post['owner_id'], $post['id'], $post['privacy_id']))
            throw new BadRequestHttpException();
        $relative_posts = $post_query->getBeforePostForId($post['year'], $post['month'], $post['day'], $post['owner_id']);

        return $this->render('view', ['model' => $post, 'models' => $relative_posts]);
    }

    public function actionEdit($id)
    {
        $post = Post::findOne(['id' => $id]);
        if (!Helper::permission_request() || Yii::$app->user->getId() !== $post['owner_id'])
            throw new BadRequestHttpException();
        $time = Time::findOne(['id' => $post['time_id']]);
        $tag_query = TagQuery::getInstance();
        $tags = Tag::toMapString($tag_query->getAll());

        $model = new PostForm();
        $this->assign_post_to_form($post, $model, $time);
        $selected_tags = $tag_query->get_tags_by_post_id($post['id']);
        $model->selected_tags = Tag::toMapString($selected_tags);
        if ($model->load(Yii::$app->request->post())) {
            $time_query = TimeQuery::getInstance();
            $model->time_id = $time_query->getId($model->day, $model->month, $model->year);
            $model->updated_at = Yii::$app->formatter->asDatetime(date('Y-d-m h:i:s'));
            $tag_query->delete_all_post_tag($model->id);
            if ($model->update($post->id)) {
                $tag_query->manage_tags($model->id, $model->tags);
                if ($model->privacy_id == 2) {
                    //TODO select friend
                    return Yii::$app->runAction('post/select-friend', ['post_id' => $model->id]);
                } else {
                    return Yii::$app->runAction('post/index');
                }
            } else {
                return $this->render('edit', ['model' => $model, 'tags' => $tags, 'is_updated' => false]);
            }
        }
        return $this->render('edit', ['model' => $model, 'tags' => $tags]);
    }

    public function actionIndex()
    {
        return Yii::$app->runAction('post/list', ['page' => 0]);
    }

    public function actionList($page)
    {
        $post_query = PostQuery::getInstance();
        $owner_id = Yii::$app->user->getId();
        $posts = $post_query->getPostByOwnerId($owner_id, $page);

        return $this->render('index', ['posts' => $posts, 'page' => $page]);
    }

    public function actionSelectFriend($post_id)
    {
        //TODO select friend
    }

    private function assign_post_to_form($post, $form, $time)
    {
        $form->id = $post->id;
        $form->title = $post->title;
        $form->content = $post->content;
        $form->comment = $post->commentable;
        $form->privacy_id = $post->privacy_id;
        $form->year = $time->year;
        $form->month = $time->month;
        $form->day = $time->day;
    }
}

frontend/views/post/_form.php
<?php
/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 10/20/2015
 * Time: 5:49 AM
 */
use dosamigos\ckeditor\CKEditor;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="post-form">
    <?php $form = ActiveForm::begin(
        [
            'id' => 'product-from',
            'options' => ['enctype' => 'multipart/form-data']
        ]); ?>
    <div class="row">
        <div class="col-lg-6">

            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'content')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'basic'
            ]) ?>

            <?= $form->field($model, 'imageFile')->fileInput(['accept' => 'image/*', 'maxSize' => 10097152]) ?>
            <br>
        </div>
        <div class="col-lg-6">
            <div class="row">
                <div class="col-md-4">
                    <?= $form->field($model, 'year') ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($model, 'month') ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($model, 'day') ?>
                </div>
            </div>

            <label>Chủ đề</label>
            <?= /** @var String[] $tags */
            Select2::widget([
                'name' => 'PostForm[tags][]',
                'value' => $model->selected_tags,
                'data' => $tags,
                'options' => ['multiple' => true],
                'pluginOptions' => [
                    'tags' => true,
                    'maximumInputLength' => 30
                ],
            ]);
            ?>
            <br>

            <div class="row">
                <div class="col-md-6">
                    <label>Mức độ riêng tư </label>
                    <br>
                    <label>
                        <select name="PostForm[privacy_id]" class="form-control">
                            <option value="1" <?= ($model->privacy_id == 1) ? 'selected' : '' ?>>Private</option>
                            <option value="2" <?= ($model->privacy_id == 2) ? 'selected' : '' ?>>Protected 1</option>
                            <option value="3" <?= ($model->privacy_id == 3) ? 'selected' : '' ?>>Protected 2</option>
                            <option value="4" <?= ($model->privacy_id == 4) ? 'selected' : '' ?>>Public</option>
                        </select>
                    </label>
                </div>
                <div class="col-md-6">
                    <label>Bình luận</label>
                    <br>

                    <div class="row">
                        <div class="radio">
                            <label>
                                <input type="radio" name="PostForm[comment]"
                                       value="true" <?= ($model->comment == true) ? 'checked' : '' ?>>
                                Có
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="PostForm[comment]"
                                       value="false" <?= ($model->comment == true) ? '' : 'checked' ?>>
                                Không
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success', 'name' => 'setting-button']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

frontend/views/post/create.php
<?php
/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 10/20/2015
 * Time: 5:49 AM
 */
$this->title = 'Viết nhật kí';
$this->params['breadcrumbs'][0] = "Quản lý nhật kí";
$this->params['breadcrumbs'][1] = $this->title;
?>
<?php
if (isset($is_created) && $is_created == false) {
    ?>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Viết bài không thành công!</h4>
        Vì một số lý do trên hệ thống mà bài viết của bạn chưa được lưu.
    </div>
    <?php
}
?>
<?= $this->render('_form', ['model' => $model, 'tags' => $tags]); ?>

frontend/views/post/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 10/21/2015
 * Time: 12:36 PM
 */
$this->title = 'Sửa nhật ký';
$this->params['breadcrumbs'][0] = "Quản lý nhật kí";
$this->params['breadcrumbs'][1] = $this->title;
?>
<?php
if (isset($is_updated) && $is_updated == false) {
    ?>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Chỉnh sửa bài viết không thành công!</h4>
        Vì một số lý do trên hệ thống mà bài viết của bạn chưa được sửa.
    </div>
    <?php
}
?>
<?= $this->render('_form', ['model' => $model, 'tags' => $tags]); ?>

frontend/views/post/index.php
<?php
/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 10/20/2015
 * Time: 10:54 AM
 */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Dah sách nhật ký';
$this->params['breadcrumbs'][0] = "Quản lý nhật kí";
$this->params['breadcrumbs'][1] = $this->title;
/** @var Array[] $posts */
$count = count($posts);
//TODO show list view
?>
<?php
foreach ($posts as $post){
?>
<div class="box box-widget">
    <div class="box-header with-border">
        <div class="user-block">
            <?php
            if (!empty($post['image'])) {
                echo Html::img(Yii::$app->request->baseUrl . '/images/' . $post['image'],
                    [
                        'alt' => "Avatar",
                        'class' => 'img-circle',
                    ]
                );

            } else {
                echo Html::img(Yii::$app->request->baseUrl . '/images/default.jpg',
                    [
                        'alt' => "Avatar",
                        'class' => 'img-circle',
                    ]
                );
            }
            ?>
            <span class="username">
                <a href="<?= \yii\helpers\Url::to(['post/view', 'id' => $post['id']]) ?>">
                    <?= $post['title'] ?></a>
                <span class="bg-red">
                        <?= $post['day'] . '.' . $post['month'] . '.' . $post['year'] ?>
                </span>
            </span>
            <span
                class="description"><?= \frontend\utils\Helper::print_privacy($post['privacy_id']) . ' - ' . $post['created_at'] ?></span>
        </div>
        <!-- /.user-block -->

        <div class="box-tools">
            <a href="<?= \yii\helpers\Url::to(['post/edit', 'id' => $post['id']]) ?>"
               class="btn btn-box-tool"
               alt="Chỉnh sửa"><i class="fa fa-edit"></i></a>
            <a href="<?= \yii\helpers\Url::to(['post/delete', 'id' => $post['id']]) ?>"
               class="btn btn-box-tool"
               alt="Xóa"><i class="fa fa-trash"></i></a>
        </div>

        <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <?php
    }
    ?>
    <?php
    if ($count >= 10) {
        echo '<div class="box-footer clearfix">';
        echo '<ul class="pagination pagination-sm no-margin pull-right">';

        if ($page > 0) {
            echo '<li><a href="' . Url::to(['post/list', 'page' => ($page - 1)]) . '">Pre</a></li>';
            echo '<li><a href="' . Url::to(['post/list', 'page' => $page]) . '">' . ($page) . '</a></li>';
        }
        if ($count == 5) {
            echo '<li><a href="' . Url::to(['post/list', 'page' => ($page + 1)]) . '">Next</a></li>';
        }

        echo '</ul>';
        echo '</div>';
    }
    ?>

frontend/views/post/select_friend.php
<?php
/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 10/20/2015
 * Time: 10:55 AM
 */

frontend/views/post/view.php
<?php
/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 10/20/2015
 * Time: 12:21 PM
 */
use yii\helpers\Html;

$post = $model;
$relative_posts = $models;
$this->title = $post['title'];
$this->params['breadcrumbs'][0] = "Danh sách nhật ký";
$this->params['breadcrumbs'][1] = $this->title;

$user_id = Yii::$app->user->getId();
$user_static = \common\models\User::findIdentity($user_id);
?>
<div class="row">
    <div class="col-lg-8">
        <div class="box box-widget">
            <div class="box-header with-border">
                <div class="user-block">
                    <?php
                    if (!empty($post['avatar'])) {
                        echo Html::img(Yii::$app->request->baseUrl . '/images/' . $post['avatar'],
                            [
                                'alt' => "Avatar",
                                'class' => 'img-circle',
                            ]
                        );

                    } else {
                        echo Html::img(Yii::$app->request->baseUrl . '/images/default.jpg',
                            [
                                'alt' => "Avatar",
                                'class' => 'img-circle',
                            ]
                        );
                    }
                    ?>
                    <span class="username"><a
                            href="<?= \yii\helpers\Url::to(['user/profile', 'id' => $post['owner_id']]) ?>">
                            <?= empty($post['full_name']) ? 'No Name' : $post['full_name'] ?></a></span>
                    <span
                        class="description"><?= \frontend\utils\Helper::print_privacy($post['privacy_id']) . ' - ' . $post['created_at'] ?></span>
                </div>
                <!-- /.user-block -->
                <?php
                if ($post['owner_id'] == $user_id) {
                    ?>
                    <div class="box-tools">
                        <a href="<?= \yii\helpers\Url::to(['post/edit', 'id' => $post['id']]) ?>"
                           class="btn btn-box-tool"
                           alt="Chỉnh sửa"><i class="fa fa-edit"></i></a>
                        <a href="<?= \yii\helpers\Url::to(['post/delete', 'id' => $post['id']]) ?>"
                           class="btn btn-box-tool"
                           alt="Xóa"><i class="fa fa-trash"></i></a>
                    </div>
                    <?php
                }
                ?>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <li class="time-label">
                    <span class="bg-red">
                        <?= $post['day'] . '.' . $post['month'] . '.' . $post['year'] ?>
                    </span>
                </li>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <?php
                        echo Html::img(Yii::$app->request->baseUrl . '/images/' . $post['image'],
                            [
                                'alt' => "photo",
                                'class' => 'img-responsive',
                            ]
                        );
                        ?>
                    </div>
                </div>
                <br>

                <p>I<?= $post['content'] ?></p>

                <span class="pull-right text-muted">3 comments</span>
            </div>
            <!-- /.box-body -->
            <div class="box-footer box-comments">
                <!-- /.box-comment -->
                <div class="box-comment">
                    <!-- User image -->
                    <img class="img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="user image">

                    <div class="comment-text">
                      <span class="username">
                        Luna Stark
                        <span class="text-muted pull-right">8:03 PM Today</span>
                      </span><!-- /.username -->
                        It is a long established fact that a reader will be distracted
                        by the readable content of a page when looking at its layout.
                    </div>
                    <!-- /.comment-text -->
                </div>
                <!-- /.box-comment -->
            </div>
            <!-- /.box-footer -->
            <div class="box-footer">
                <form action="#" method="post">
                    <?php
                    echo Html::img(Yii::$app->request->baseUrl . '/images/' . $user_static['image'],
                        [
                            'alt' => "photo",
                            'class' => 'img-responsive img-circle img-sm',
                        ]
                    );
                    ?>
                    <!-- .img-push is used to add margin to elements next to floating images -->
                    <div class="img-push">
                        <input type="text" class="form-control input-sm" placeholder="Press enter to post comment">
                    </div>
                </form>
            </div>
            <!-- /.box-footer -->
        </div>
    </div>
    <div class="col-lg-4">
        <?php
        foreach ($relative_posts as $relative_post) {
            ?>
            <div class="box box-widget">
                <div class="box-header with-border">
                    <div class="user-block">
                        <?php
                        if (!empty($relative_post['image'])) {
                            echo Html::img(Yii::$app->request->baseUrl . '/images/' . $relative_post['image'],
                                [
                                    'alt' => "Image",
                                    'class' => 'img-circle',
                                ]
                            );

                        } else {
                            echo Html::img(Yii::$app->request->baseUrl . '/images/default_post.jpg',
                                [
                                    'alt' => "Image",
                                    'class' => 'img-circle',
                                ]
                            );
                        }
                        ?>
                        <span class="username"> <a
                                href="<?= \yii\helpers\Url::to(['post/view', 'id' => $relative_post['id']]) ?>"><?= $relative_post['title'] ?></a></span>
                        <span
                            class="description"><?= \frontend\utils\Helper::print_privacy($relative_post['privacy_id']) ?></span>
                    </div>
                </div>
                <div class="box-body">
                    <span class="bg-blue">
                        <?= $relative_post['day'] . '.' . $relative_post['month'] . '.' . $relative_post['year'] ?>
                    </span>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
</div>